require("configs.settings")
require("plugins.plugins")
require("configs.mappings")

require("configs.lualine-config")
require("configs.nvimtree-config")
require("configs.treesitter-config")
require("configs.indent-blankline-config")
require("configs.bufferline-config")
require("configs.smart-splits-config")
require("configs.telescope-config")
require("configs.gitsigns-config")
require("configs.autotag-config")
require("configs.pantran-config")
require("configs.lsp-config")